mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetView,
)
from . import views
from django.urls import reverse_lazy

app_name = "polls"

urlpatterns = [
    path("", views.quotes, name="quotes"),
    path("author/<int:author_id>/", views.author_detail, name="author_detail"),
    path("filtered_quotes/<str:tag>/", views.quotes_by_tag, name="filtered_quotes"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        views.custom_login,
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    # password reset urls:
    path(
        "password_reset/",
        PasswordResetView.as_view(
            success_url=reverse_lazy("polls:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("polls:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

mysite/polls/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(blank=False, unique=True)
    born_date = models.CharField(blank=True)
    born_location = models.CharField(blank=True)
    description = models.CharField(blank=True)


class Quote(models.Model):
    tags = models.TextField(blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.CharField(blank=False)

mysite/polls/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login
from collections import Counter

from .models import Quote, Author
from .forms import SignUpForm

from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm


def quotes(request):
    quotes_list = Quote.objects.all()
    tag_counts = Counter()

    for quote in quotes_list:
        extracted_tags = [tag.strip("{}") for tag in quote.tags.split(",")]
        tag_counts.update(extracted_tags)

    top_tags = [tag for tag, _ in tag_counts.most_common(10)]

    return render(
        request,
        "polls/quotes.html",
        {"quotes_list": quotes_list, "top_tags": top_tags},
    )


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "polls/author_detail.html", {"author": author})


def quotes_by_tag(request, tag):
    quotes_by_tag_list = Quote.objects.filter(tags__icontains=tag)
    return render(
        request,
        "polls/quotes_by_tag.html",
        {"quotes_by_tag_list": quotes_by_tag_list, "clicked_tag": tag},
    )


def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("polls:quotes")
    else:
        form = SignUpForm()

    return render(request, "polls/register.html", {"form": form})


def custom_login(request):
    password_reset_url = reverse_lazy("polls:password_reset")

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("polls:quotes")
    else:
        form = AuthenticationForm()

    return render(
        request,
        "polls/custom_login.html",
        {"password_reset_url": password_reset_url, "form": form},
    )

mysite/polls/templates/polls/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Detail</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  <h1>Author Detail</h1>
  {% if author %}
    <h2>{{ author.fullname }}</h2>
    <p>Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>

  {% else %}
    <p>No author details available.</p>
  {% endif %}
</body>
</html>

mysite/polls/templates/polls/custom_login.html
{% block content %}
  <h2>Login</h2>
  <form method="post" action="{% url 'polls:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'polls:register' %}">Register</a></p>
  <p>Forgot your password? <a href="{% url 'polls:password_reset' %}">Reset Password</a></p>
{% endblock %}

mysite/polls/templates/polls/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}/password_reset_confirm/{{ uid }}/{{ token }}/

{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

mysite/polls/templates/polls/quotes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quotes</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  <h1>Quotes</h1>
  {% if quotes_list %}
    <ul>
      {% for quote in quotes_list %}
        <li>
          {{ quote.quote }} by
          <a href="{% url 'polls:author_detail' author_id=quote.author.id %}">{{ quote.author.fullname }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No quotes are available.</p>
  {% endif %}

  <h2>Top 10 tags</h2>
  {% if top_tags %}
    <ul>
      {% for tag in top_tags %}
        <li><a href="{% url 'polls:filtered_quotes' tag %}">{{ tag }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No tags are available.</p>
  {% endif %}


  {% if user.is_authenticated %}
    <!-- Display the buttons only for authenticated users -->
    <a href="{% url 'admin:polls_author_add' %}">Add Author</a>
    <a href="{% url 'admin:polls_quote_add' %}">Add Quote</a>
    <form action="{% url 'polls:logout' %}" method="post" style="display: box;">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    
  {% endif %}

  {% if not user.is_authenticated %}
    <!-- Display the register button only for non authenticated users -->
    <form action="{% url 'polls:register' %}" method="get" style="display: box;">
        {% csrf_token %}
        <button type="submit">Register</button>
    </form>
    <form action="{% url 'polls:login' %}" method="get" style="display:box;">
        {% csrf_token %}
        <button type="submit">Login</button>
    </form>
  {% endif %}
</body>
</html>

mysite/polls/templates/polls/quotes_by_tag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Detail</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  <h2>Quotes by tag: {{clicked_tag}} </h2>
    {% for quote in quotes_by_tag_list %}
      <p>Quotes: {{ quote.quote }}</p>
    {% endfor %}
  <form action="{% url 'polls:quotes' %}" method="post" style="display: box;">
        {% csrf_token %}
        <button type="submit">Home</button>
    </form>
</body>
</html>

mysite/polls/templates/polls/register.html
<!DOCTYPE html>
<html>
<head>
    <title>User Registration - My Site</title>
    {% load static %}
</head>
<body class="change-list">
    <div id="content" class="colMS">
        <h1>User Registration</h1>
        <div id="container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Register</button>
            </form>
            <p>Already have an account? <a href="{% url 'polls:login' %}">Login</a></p>
        </div>
    </div>
</body>
</html>